openapi: 3.1.0
info:
  title: Test API
  description: Testing complex query parameters
  version: 0.0.1
  license: 
    name: MIT
    url: https://nobody.org

servers:
  - url: http://127.0.0.0:3000

tags: 
  - name: Users
    description: Operations for users
  - name: Other
    description: other stuff

paths:
  /users/{userId}:
    $ref: paths/api_users_userid.yaml
  /posts/{postId}:
    $ref: paths/api_posts_postId.yaml
  /posts:
    $ref: paths/api_posts.yaml
  /comments/{commentId}:
    $ref: paths/api_comments_commentId.yaml
