openapi: 3.1.0
servers:
  - url: http://127.0.0.0:3000
info: 
   title: Test API
   version: 1.0.0
   license:
      name: MIT
      identifier: MIT

components:
  parameters:
    CommentIdParam:
      in: path
      name: commentId
      required: true
      schema:
        $ref: Fields.yaml#/components/schemas/CommentId
        description: A unique identifier for a comment
  schemas:
    Comment:
      title: Comment
      type: object
      properties:
        commentId:
          $ref: Fields.yaml#/components/schemas/CommentId
          description: A unique identifier for a comment (override)
        commentTx:
          $ref: Fields.yaml#/components/schemas/CommentTx
        commenter:
          $ref: User.yaml#/components/schemas/User
      required:
        - commentId
        - commentTx
        - commenter
